package com.gcs.supporter.mavlink.message.parser;

public enum MavLinkParsingState {
    MAVLINK_PARSE_STATE_UNINIT,
    MAVLINK_PARSE_STATE_IDLE,
    MAVLINK_PARSE_STATE_GOT_STX,
    MAVLINK_PARSE_STATE_GOT_LENGTH,
    MAVLINK_PARSE_STATE_GOT_INCOMPAT_FLAGS, // MAVLink 2
    MAVLINK_PARSE_STATE_GOT_COMPAT_FLAGS, // MAVLink 2
    MAVLINK_PARSE_STATE_GOT_SEQ,
    MAVLINK_PARSE_STATE_GOT_SYSID,
    MAVLINK_PARSE_STATE_GOT_COMPID,
    MAVLINK_PARSE_STATE_GOT_MSGID1,
    MAVLINK_PARSE_STATE_GOT_MSGID2, // MAVLink 2
    MAVLINK_PARSE_STATE_GOT_MSGID3, // MAVLink 2
    MAVLINK_PARSE_STATE_GOT_CRC1,
    MAVLINK_PARSE_STATE_GOT_CRC2, // MAVLink 2
    MAVLINK_PARSE_STATE_GOT_PAYLOAD,
    MAVLINK_PARSE_STATE_GOT_SIGNATURE, // MAVLink 2
}
