version: '2'

services:
  zookeeper:
    container_name: gcs_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      gcs:
        ipv4_address: 172.20.0.100

  kafka:
    container_name: gcs_kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.101
      KAFKA_CREATE_TOPICS: serverToAgent:1:1,agentToServer:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      gcs:
        ipv4_address: 172.20.0.101

  mysql:
    container_name: mysql
    image: dltmd202/gcs_mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      gcs:

  mav-core:
    container_name: mav-core
    image: dltmd202/mav-core:arm
    ports:
      - 9751:9751/udp
    environment:
      spring.kafka.bootstrap-servers: 172.20.0.101:9092
      gcs.address.agent.ip: 192.168.35.161
      gcs.address.agent.port: 9751
      logging.file: /api-logs/orders-ws.log
      file.dir: /files
    volumes:
      - ./conf_files:/files
    depends_on:
      - kafka
    networks:
      gcs:

  gcs:
    container_name: gcs
    image: dltmd202/monolith:arm
    ports:
      - 8080:8080
    environment:
      server.port: 8080
      spring.datasource.url: jdbc:mysql://mysql:3306/gcs
      spring.datasource.username: root
      spring.datasource.password: 1234
      spring.kafka.bootstrap-servers: 172.20.0.101:9092
      logging.file: /api-logs/orders-ws.log
      file.dir: /files
    volumes:
      - ./conf_files:/files
    depends_on:
      - kafka
      - mysql
    networks:
      gcs:
        ipv4_address: 172.20.0.4


  client:
    container_name: gcs_client
    image: dltmd202/client:arm
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_END_POINT: http://192.168.35.161:8080
      REACT_APP_REALTIME_END_POINT: ws://192.168.35.161:8080
      REACT_APP_GOOGLE_MAP_KEY: AIzaSyDJVwYS6Jf_KFZA_x1Qhoo2D5FzBsN9Fmk
    depends_on:
      - gcs
    networks:
      gcs:

networks:
  gcs:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1