version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      gcs:
        ipv4_address: 172.20.0.100

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.101
      KAFKA_CREATE_TOPICS: serverToAgent:1:1,agentToServer:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      gcs:
        ipv4_address: 172.20.0.101

  mav-core:
    container_name: mav-core
    image: dltmd202/mav-core:arm
    ports:
      - 9751:9751/udp
    environment:
      spring.kafka.bootstrap-servers: 172.20.0.101:9092
      gcs.address.agent.ip: 192.168.35.161
      gcs.address.agent.port: 9751
      logging.file: /api-logs/orders-ws.log
      file.dir: /files
    volumes:
      - ./conf_files:/files
    depends_on:
      - kafka

networks:
  gcs:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1