/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE PIKSI_POS_LLH PACKING
package com.MAVLink.swarm;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * piksi_msg_pos_llh
 */
public class msg_piksi_pos_llh extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_PIKSI_POS_LLH = 187;
    public static final int MAVLINK_MSG_LENGTH = 30;
    private static final long serialVersionUID = MAVLINK_MSG_ID_PIKSI_POS_LLH;

    
    /**
     * lat
     */
    @Description("lat")
    @Units("")
    public double lat;
    
    /**
     * lon
     */
    @Description("lon")
    @Units("")
    public double lon;
    
    /**
     * height
     */
    @Description("height")
    @Units("")
    public double height;
    
    /**
     * h_accuracy
     */
    @Description("h_accuracy")
    @Units("")
    public int h_accuracy;
    
    /**
     * v_accuracy
     */
    @Description("v_accuracy")
    @Units("")
    public int v_accuracy;
    
    /**
     * n_sats
     */
    @Description("n_sats")
    @Units("")
    public short n_sats;
    
    /**
     * flags
     */
    @Description("flags")
    @Units("")
    public short flags;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_PIKSI_POS_LLH;

        packet.payload.putDouble(lat);
        packet.payload.putDouble(lon);
        packet.payload.putDouble(height);
        packet.payload.putUnsignedShort(h_accuracy);
        packet.payload.putUnsignedShort(v_accuracy);
        packet.payload.putUnsignedByte(n_sats);
        packet.payload.putUnsignedByte(flags);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a piksi_pos_llh message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.lat = payload.getDouble();
        this.lon = payload.getDouble();
        this.height = payload.getDouble();
        this.h_accuracy = payload.getUnsignedShort();
        this.v_accuracy = payload.getUnsignedShort();
        this.n_sats = payload.getUnsignedByte();
        this.flags = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_piksi_pos_llh() {
        this.msgid = MAVLINK_MSG_ID_PIKSI_POS_LLH;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_piksi_pos_llh( double lat, double lon, double height, int h_accuracy, int v_accuracy, short n_sats, short flags) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_POS_LLH;

        this.lat = lat;
        this.lon = lon;
        this.height = height;
        this.h_accuracy = h_accuracy;
        this.v_accuracy = v_accuracy;
        this.n_sats = n_sats;
        this.flags = flags;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_piksi_pos_llh( double lat, double lon, double height, int h_accuracy, int v_accuracy, short n_sats, short flags, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_POS_LLH;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.lat = lat;
        this.lon = lon;
        this.height = height;
        this.h_accuracy = h_accuracy;
        this.v_accuracy = v_accuracy;
        this.n_sats = n_sats;
        this.flags = flags;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_piksi_pos_llh(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_POS_LLH;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                  
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_PIKSI_POS_LLH - sysid:"+sysid+" compid:"+compid+" lat:"+lat+" lon:"+lon+" height:"+height+" h_accuracy:"+h_accuracy+" v_accuracy:"+v_accuracy+" n_sats:"+n_sats+" flags:"+flags+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_PIKSI_POS_LLH";
    }
}
        