/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE PIKSI_GLO_BIASES PACKING
package com.MAVLink.swarm;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * piksi_glo_biases
 */
public class msg_piksi_glo_biases extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_PIKSI_GLO_BIASES = 186;
    public static final int MAVLINK_MSG_LENGTH = 14;
    private static final long serialVersionUID = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;

    
    /**
     * glo biases sender id
     */
    @Description("glo biases sender id")
    @Units("")
    public int sender_id;
    
    /**
     * msg_type
     */
    @Description("msg_type")
    @Units("")
    public int msg_type;
    
    /**
     * glo biases data length
     */
    @Description("glo biases data length")
    @Units("")
    public short len;
    
    /**
     * glo biases data
     */
    @Description("glo biases data")
    @Units("")
    public short data[] = new short[9];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;

        packet.payload.putUnsignedShort(sender_id);
        packet.payload.putUnsignedShort(msg_type);
        packet.payload.putUnsignedByte(len);
        
        for (int i = 0; i < data.length; i++) {
            packet.payload.putUnsignedByte(data[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a piksi_glo_biases message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sender_id = payload.getUnsignedShort();
        this.msg_type = payload.getUnsignedShort();
        this.len = payload.getUnsignedByte();
        
        for (int i = 0; i < this.data.length; i++) {
            this.data[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_piksi_glo_biases() {
        this.msgid = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_piksi_glo_biases( int sender_id, int msg_type, short len, short[] data) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;

        this.sender_id = sender_id;
        this.msg_type = msg_type;
        this.len = len;
        this.data = data;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_piksi_glo_biases( int sender_id, int msg_type, short len, short[] data, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sender_id = sender_id;
        this.msg_type = msg_type;
        this.len = len;
        this.data = data;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_piksi_glo_biases(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_PIKSI_GLO_BIASES;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_PIKSI_GLO_BIASES - sysid:"+sysid+" compid:"+compid+" sender_id:"+sender_id+" msg_type:"+msg_type+" len:"+len+" data:"+data+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_PIKSI_GLO_BIASES";
    }
}
        