spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  consumer:
    properties:
      enable.idempotence: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gcs
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

google-map:
  key: AIzaSyDJVwYS6Jf_KFZA_x1Qhoo2D5FzBsN9Fmk

ros2:
  ros2-web-bridge:
    web-socket:
      schema: ws
      ip: 218.150.182.119
      port: 10081


file:
  dir: /Users/mac/Documents/LECTURE/graduation/graduation/gcs/files/

gcs:
  kafka:
    topics:
      serverToAgent: serverToAgent
      agentToServer: agentToServer
    polling:
      period: 100
    consumer:
      group: agentToServer
  address:
    agent:
      ip: 127.0.0.1
      port: 9750

    agents:
      1:
        ip: 127.0.0.1
        port: 9751
      2:
        ip: 127.0.0.1
        port: 9751
      96:
        ip: 127.0.0.1
        port: 9751

    gcs:
      ip: 192.168.35.41
      port: 9750

jwt:
  token:
    header: Authorization
    issuer: gcs
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0