gcs:
  kafka:
    topics:
      serverToAgent: serverToAgent
      agentToServer: agentToServer
    polling:
      period: 100
    consumer:
      group: serverToAgent

  address:
    agent:
      ip: 127.0.0.1
      port: 9750

    agents:
      1:
        ip: 127.0.0.1
        port: 9751
      2:
        ip: 127.0.0.1
        port: 9751
      96:
        ip: 127.0.0.1
        port: 9751

    gcs:
      ip: 192.168.35.41
      port: 9750
