/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Enumeration of distance sensor types
 */
public class SCENARIO_CMD_ENUM {
   public static final int SCENARIO_CMD_SET_START_TIME = 0; /* set start time for scenario  (param1: start_time) | */
   public static final int SCENARIO_CMD_SET_RELATIVE_POS = 1; /* set relative position (param1 : x, param2: y) | */
   public static final int SCENARIO_CMD_SELECT_SCENARIO_FILE = 2; /* set scenario file name (param5 : file name) | */
   public static final int SCENARIO_CMD_STOP_SCENARIO = 3; /* stop scenario | */
   public static final int SCENARIO_CMD_EMERGENCY_LAND = 4; /* land | */
   public static final int SCENARIO_CMD_SET_CONFIGS = 5; /* set vairous configurations param1: base vehicle pos x, param2: base vehicle pos y, param5: scenario file name | */
   public static final int SCENARIO_CMD_RESET_CONFIGS = 6; /* reset configurations | */
   public static final int SCENARIO_CMD_ENUM_ENUM_END = 7; /*  | */
}
            