server:
  port: 0

spring:
  application:
    name: user



jwt:
  token:
    header: Authorization
    issuer: gcs
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0

file:
  dir: /Users/mac/Documents/LECTURE/graduation/graduation/gcs/files/

session:
  fileLoader: conf_load


google-map:
  key: AIzaSyDJVwYS6Jf_KFZA_x1Qhoo2D5FzBsN9Fmk


ros2:
  ros2-web-bridge:
    web-socket:
      schema: ws
      ip: 218.150.182.119
      port: 10081

coordinate:
  initial:
    lat: 36.766689
    lng: 127.281952
    alt: 10